modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"

[[mods]]
modId="test"
version="${file.jarVersion}"
displayName="Test Mod"
logoFile="test.png"
credits="Thanks for this example mod goes to Java"
authors="Love, Cheese and small house plants"
description=""

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
